[build]
  command = "echo 'No build required'"
  publish = "."

[dev]
  command = "python run.py"
  port = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
